configs:
- id: easytravel-prod_easytravel-angular-loadgen_trace_context_logs
  config:
    name: easytravel-prod_easytravel-angular-loadgen_trace_context_logs
    template: feature_instrument_template.json
    skip: false
    parameters:
      enabled: true 
      key: SENSOR_JAVA_LOG_ENRICHMENT
  type:
    settings:
      schema: builtin:oneagent.features
      schemaVersion: 1.5.7
      scope: PROCESS_GROUP-DA37483DD34A2528
- id: easytravel-prod_easytravel-angular-loadgen_trace_context_unstructured_logs
  config:
    name: easytravel-prod_easytravel-angular-loadgen_trace_context_unstructured_logs
    template: feature_template.json
    skip: false
    parameters:
      enabled: true 
      key: JAVA_LOG_ENRICHMENT_UNSTRUCTURED
  type:
    settings:
      schema: builtin:oneagent.features
      schemaVersion: 1.5.7
      scope: PROCESS_GROUP-DA37483DD34A2528